//Parameter Types
#define PARAM_STRING  1
#define PARAM_BOOLEAN 2
#define PARAM_INT 3
#define PARAM_SENSORINPUT 4
#define PARAM_SENSOROUTPUT 5
#define PARAM_SCHEDULE 6
#define PARAM_MAPPING 7
#define PARAM_ARRAY 8
#define PARAM_SENSORINPUTARRAY 9
#define PARAM_SENSOROUTPUTARRAY 10
#define PARAM_RO 11
#define PARAM_SELECT 12
#define PARAM_MODULELOGDATA 13
#define PARAM_MODULELOGEVENT 14

//Parameter Options
#define POPT_NONE        0
#define POPT_RELOAD      (1<<0)
#define POPT_MODRELOAD   (1<<0)
